### ISSUE TITLE
Nefunguje stránkování

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/altoEditorClient#1]
na obrazovkách Moje editace, Revize ani Správa procesů nefunguje správně stránkování

- [x] Nejde vybrat, kolik se má na stránce ukázat položek (vybrat to jde, ale nic se nestane)
- [x] Nefunguje posouvání mezi stránkami
- [x] Ovládací prvky jsou v angličtině, přestože je rozhraní přepnuté do češtiny

**Comment by kerschfilip** [comment]
Funguje, ale ovládací prvky jsou stále anglicky  
<img width="400" alt="image" src="https://github.com/ceskaexpedice/altoEditorClient/assets/57805328/6ebba3ae-c9a7-4153-aa22-ccd459bc868a">

**Comment by albertoh** [comment]
Lokalizace hotova

**Comment by kerschfilip** [comment]
OK, díky
