### ISSUE TITLE
Zobrazovat Název/cestu

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/altoEditorClient#2]
V rámci obrazovky editace by bylo fajn vidět, co edituju - název monografie nebo u periodika cestu titul/ročník/číslo

**Comment by kerschfilip** [comment]
V editaci OK, můžeme to prosím doplnit i do Revize, tam teď vidím jen UUID:  
<img width="1165" alt="image" src="https://github.com/ceskaexpedice/altoEditorClient/assets/57805328/a448893b-59e2-4111-b4e6-2e7252c870a2">

**Comment by albertoh** [comment]
Pridano
