### ISSUE TITLE
Doplnit zpětnou vazbu pro uživatele

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/altoEditorClient#4]
Napříč aplikací chybí zpětná vazba u některých tlačítek - kliknu na ně, ale nedostanu zpět žádnou informaci, jestli se něco stalo:

- [x] Na obrazovce editace se po kliknutí na `Uložit` změny uloží, ale nejsem o tom nijak informován
- [ ] stejně tak se nic neděje když kliknu na `PERO` - mělo by mi to buď ukázat lištu, že se obrázek zpravovaná, nebo nějakou chybovou hlášku, že to teď není k dispozici.
  - [ ] ke zvážení je, jestli tahle obrazovka bude k dispozici běžným čtenářům tlačítko přejmenovat - např. na `Vygenerovat novou textovou vrstvu`. PERO jim asi moc neřekne
- [x] při uložení změn v textové vrstvě v Revizi přes ikonu diskety taky nedostanu žádnou zpětnou vazbu, stejně tak by měla být doplněna i při odeslání do Krameria/ProArcu

**Comment by kerschfilip** [comment]
zpětná vazba při ukládání je OK, díky

Na obrazovce Moje editace teď chybí to tlačítko "PERO"

**Comment by albertoh** [comment]
Tlacitko PERO je jen v pripade, ze objekt jeste nebyl generovan

Zavreno na zaklade schuzky.

**Comment by albertoh** [comment]
Zavriram na zaklade schuzky.
